INSERT INTO Exame
(Nome, Slug, Information, Preparation, Procedimento_Id, Criado_em, Atualizado_em)
VALUES
('Abdome infantil para refluxo','abdome-infantil-para-refluxo','Ultrassonografia utilizada para avaliação de refluxo gastroesofágico em crianças.','Seguir orientação médica específica. Em alguns casos pode ser solicitado jejum curto.',1,NOW(),NOW()),
('Abdome total infantil','abdome-total-infantil','Exame para avaliação dos órgãos abdominais da criança.','Jejum de 4 a 6 horas conforme idade da criança.',1,NOW(),NOW()),
('Aparelho urinário','aparelho-urinario','Exame para análise de rins, ureteres e bexiga.','Beber aproximadamente 4 a 6 copos de água 1 hora antes e não urinar.',1,NOW(),NOW()),
('Avaliação de sinovite transitória','avaliacao-de-sinovite-transitoria','Exame utilizado para detectar líquido e inflamação articular.','Não necessita preparo.',1,NOW(),NOW()),
('Bolsa testicular','bolsa-testicular','Exame para avaliação dos testículos e estruturas adjacentes.','Não necessita preparo.',1,NOW(),NOW()),
('Cervical','cervical','Avalia estruturas do pescoço como linfonodos e glândulas.','Não necessita preparo.',1,NOW(),NOW()),
('Coluna','coluna','Exame para análise de estruturas musculares e tecidos próximos à coluna.','Não necessita preparo.',1,NOW(),NOW()),
('Mamária infantil','mamaria-infantil','Exame utilizado para avaliação das estruturas mamárias infantis.','Não necessita preparo.',1,NOW(),NOW()),
('Pélvica infantil','pelvica-infantil','Exame para avaliação de órgãos pélvicos infantis.','Bexiga cheia conforme orientação médica.',1,NOW(),NOW()),
('Quadril (RN – displasia do desenvolvimento)','quadril-rn-displasia-do-desenvolvimento','Exame utilizado para rastrear alterações no desenvolvimento do quadril.','Não necessita preparo.',1,NOW(),NOW()),
('Região inguinal bilateral','regiao-inguinal-bilateral','Exame utilizado para avaliar hérnias e alterações na região inguinal.','Não necessita preparo.',1,NOW(),NOW()),
('Suturas cranianas','suturas-cranianas','Exame utilizado para avaliação das suturas do crânio.','Não necessita preparo.',1,NOW(),NOW()),
('Tireoide','tireoide','Exame para avaliação da glândula tireoide.','Não necessita preparo.',1,NOW(),NOW()),
('Transfontanela','transfontanela','Ultrassonografia cerebral realizada pela fontanela do bebê.','Não necessita preparo.',1,NOW(),NOW()),
('Avaliação do colo uterino','avaliacao-do-colo-uterino','Exame para avaliação do comprimento e características do colo uterino.','Não necessita preparo específico.',2,NOW(),NOW()),
('Gestacional','gestacional','Ultrassonografia para acompanhamento da gestação.','Pode ser solicitado enchimento da bexiga dependendo da idade gestacional.',2,NOW(),NOW()),
('Gestacional com Doppler','gestacional-com-doppler','Exame que avalia o fluxo sanguíneo materno e fetal.','Não necessita preparo específico.',2,NOW(),NOW()),
('Gestacional inicial','gestacional-inicial','Exame para avaliação das fases iniciais da gravidez.','Bexiga moderadamente cheia.',2,NOW(),NOW()),
('Morfológico 1º trimestre','morfologico-1-trimestre','Exame detalhado para avaliação anatômica fetal.','Não necessita preparo.',2,NOW(),NOW()),
('Morfológico 2º trimestre','morfologico-2-trimestre','Exame detalhado da anatomia fetal.','Não necessita preparo.',2,NOW(),NOW()),
('Neurossonografia fetal','neurossonografia-fetal','Exame específico para análise cerebral fetal.','Não necessita preparo.',2,NOW(),NOW()),
('Avaliação de DIU 3D','avaliacao-de-diu-3d','Exame para verificar posicionamento do dispositivo intrauterino.','Não necessita preparo.',3,NOW(),NOW()),
('Contagem de folículos','contagem-de-foliculos','Exame para avaliação da reserva ovariana.','Não necessita preparo específico.',3,NOW(),NOW()),
('Doppler ginecológico','doppler-ginecologico','Exame para avaliação do fluxo sanguíneo ginecológico.','Não necessita preparo.',3,NOW(),NOW()),
('Transabdominal','transabdominal','Ultrassonografia ginecológica por via abdominal.','Beber água e manter a bexiga cheia.',3,NOW(),NOW()),
('Transvaginal','transvaginal','Ultrassonografia realizada por via vaginal.','Não necessita preparo.',3,NOW(),NOW()),
('Transvaginal 3D','transvaginal-3d','Exame tridimensional para análise ginecológica.','Não necessita preparo.',3,NOW(),NOW()),
('Transpubiana','transpubiana','Exame realizado através da região suprapúbica.','Bexiga cheia.',3,NOW(),NOW()),
('Bolsa testicular','bolsa-testicular-urologia','Avaliação dos testículos e estruturas associadas.','Não necessita preparo.',4,NOW(),NOW()),
('Próstata (via abdominal)','prostata-via-abdominal','Exame para avaliação prostática.','Bexiga cheia.',4,NOW(),NOW()),
('Rins e vias urinárias com resíduo pós-miccional','rins-e-vias-urinarias-com-residuo-pos-miccional','Exame para análise do trato urinário antes e após esvaziamento da bexiga.','Beber água e manter a bexiga cheia.',4,NOW(),NOW()),
('Abdome superior e abdome total','abdome-superior-e-abdome-total','Exame dos órgãos abdominais.','Jejum de 6 a 8 horas.',5,NOW(),NOW()),
('Axilas','axilas','Exame para avaliação de linfonodos e tecidos axilares.','Não utilizar cremes ou desodorantes antes do exame.',5,NOW(),NOW()),
('Hérnias','hernias','Exame para investigação de hérnias.','Não necessita preparo.',5,NOW(),NOW()),
('Mama','mama','Exame para avaliação mamária.','Não utilizar cremes na região.',5,NOW(),NOW()),
('Parede abdominal','parede-abdominal','Exame para avaliação de hérnias e alterações da parede abdominal.','Não necessita preparo.',5,NOW(),NOW()),
('Pescoço e região cervical','pescoco-e-regiao-cervical','Exame para avaliação cervical.','Não necessita preparo.',5,NOW(),NOW()),
('Região inguinal','regiao-inguinal','Exame para avaliação de hérnias e alterações locais.','Não necessita preparo.',5,NOW(),NOW()),
('Rins e vias urinárias','rins-e-vias-urinarias','Exame para avaliação renal.','Bexiga cheia.',5,NOW(),NOW()),
('Tireoide','tireoide-geral','Exame para análise da tireoide.','Não necessita preparo.',5,NOW(),NOW()),
('Lesões traumáticas e inflamatórias','lesoes-traumaticas-e-inflamatorias','Exame musculoesquelético para avaliação de lesões.','Não necessita preparo.',6,NOW(),NOW()),
('Punho','punho','Exame para avaliação das estruturas do punho.','Não necessita preparo.',6,NOW(),NOW()),
('Ombros','ombros','Exame para avaliação muscular e articular do ombro.','Não necessita preparo.',6,NOW(),NOW()),
('Tendões','tendoes','Exame para avaliação tendínea.','Não necessita preparo.',6,NOW(),NOW()),
('Tornozelos','tornozelos','Exame para avaliação articular e ligamentar.','Não necessita preparo.',6,NOW(),NOW());