CREATE TABLE Usuarios (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    Nome VARCHAR(150) NOT NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    Senha VARCHAR(255) NOT NULL,

    Funcao ENUM('admin', 'doctor', 'secretary') NOT NULL DEFAULT 'secretary',
    Ativo BOOLEAN NOT NULL DEFAULT TRUE,

    Criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX (Email),
    INDEX (Ativo)
);

CREATE TABLE Doutor (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(150) NOT NULL,
    Criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE DoutorHorario (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DoutorId INT UNSIGNED NOT NULL,
    DiaSemana TINYINT NOT NULL, -- 0=Domingo
    HoraInicio TIME NOT NULL,
    HoraFim TIME NOT NULL,

    FOREIGN KEY (DoutorId) REFERENCES Doutor(Id)
);

CREATE TABLE DoutorHorarioIndisponivel (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DoutorId INT UNSIGNED NOT NULL,
    Data DATE NOT NULL,

    FOREIGN KEY (DoutorId) REFERENCES Doutor(Id)
);

CREATE TABLE Procedimento (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    Nome VARCHAR(150) NOT NULL,
    Slug VARCHAR(150) NOT NULL UNIQUE,

    Criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Exame (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    Nome VARCHAR(150) NOT NULL,
    Slug VARCHAR(150) NOT NULL UNIQUE,
    Information TEXT NOT NULL,
    Preparation TEXT NOT NULL,

    Procedimento_Id INT UNSIGNED NOT NULL,

    Criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
        ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (Procedimento_Id)
        REFERENCES Procedimento(Id)
        ON DELETE CASCADE
);

CREATE TABLE Doutor_Exame (
    Doutor_Id INT UNSIGNED NOT NULL,
    Exame_Id INT UNSIGNED NOT NULL,

    PRIMARY KEY (Doutor_Id, Exame_Id),

    FOREIGN KEY (Doutor_Id)
        REFERENCES Doutor(Id)
        ON DELETE CASCADE,

    FOREIGN KEY (Exame_Id)
        REFERENCES Exame(Id)
        ON DELETE CASCADE
);

CREATE TABLE Agendamento (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    Doutor_Id INT UNSIGNED NOT NULL,
    Exame_Id INT UNSIGNED NOT NULL,

    Data DATE NOT NULL,
    Horario_inicio TIME NOT NULL,
    Horario_fim TIME NOT NULL,

    Telefone VARCHAR(20) NOT NULL,

    Criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (Doutor_Id)
        REFERENCES Doutor(Id)
        ON DELETE CASCADE,

    FOREIGN KEY (Exame_Id)
        REFERENCES Exame(Id)
        ON DELETE CASCADE,

    UNIQUE (Doutor_Id, Data, Horario_inicio)
);

CREATE TABLE Avaliacao (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    Nota TINYINT UNSIGNED NOT NULL,
    Texto VARCHAR(500),

    Status BOOLEAN NOT NULL DEFAULT TRUE,

    Criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CHECK (Nota BETWEEN 1 AND 5)
);

CREATE INDEX idx_doutor_nome ON Doutor(Nome);
CREATE INDEX idx_exame_nome ON Exame(Nome);
CREATE INDEX idx_procedimento_nome ON Procedimento(Nome);
CREATE INDEX idx_agendamento_data ON Agendamento(Data);
CREATE INDEX idx_agendamento_doutor ON Agendamento(Doutor_Id);
CREATE INDEX idx_avaliacao_status ON Avaliacao(Status);