import {
  Doctor,
  Exam,
  Procedure,
  Appointment,
  Review,
  User,
  DashboardModule,
} from './types';

export const mockDoctors: Doctor[] = [
  {
    id: 1,
    name: 'Dra. Maria Silva',
    graduation: 'Ginecologista | CRM: 12345',
    createdAt: '2024-01-15',
    updatedAt: '2024-06-01',
  },
  {
    id: 2,
    name: 'Dra. Ana Santos',
    graduation: 'Obstetriz | CRM: 12346',
    createdAt: '2024-02-10',
    updatedAt: '2024-05-28',
  },
  {
    id: 3,
    name: 'Dra. Paula Costa',
    graduation: 'Ginecologista Clínica | CRM: 12347',
    createdAt: '2024-03-05',
    updatedAt: '2024-06-02',
  },
  {
    id: 4,
    name: 'Dra. Juliana Oliveira',
    graduation: 'Especialista em Reprodução Humana | CRM: 12348',
    createdAt: '2024-04-20',
    updatedAt: '2024-05-30',
  },
];

export const mockExams: Exam[] = [
  {
    id: 1,
    name: 'Ultrassom Pélvico',
    slug: 'ultrassom-pelvico',
    information: 'Exame de ultrassom da região pélvica',
    preparation: 'Bexiga cheia, sem preparo especial',
    procedureId: 1,
    createdAt: '2024-01-20',
    updatedAt: '2024-05-15',
  },
  {
    id: 2,
    name: 'Colposcopia',
    slug: 'colposcopia',
    information: 'Visualização do colo do útero',
    preparation: 'Não estar menstruada',
    procedureId: 2,
    createdAt: '2024-02-10',
    updatedAt: '2024-05-20',
  },
  {
    id: 3,
    name: 'Mamografia',
    slug: 'mamografia',
    information: 'Radiografia das mamas',
    preparation: 'Sem desodorante ou talco',
    procedureId: 3,
    createdAt: '2024-03-15',
    updatedAt: '2024-05-25',
  },
  {
    id: 4,
    name: 'Ressonância Magnética',
    slug: 'ressonancia-magnetica',
    information: 'Ressonância magnética de órgãos reprodutivos',
    preparation: 'Sem objetos metálicos',
    procedureId: 1,
    createdAt: '2024-04-10',
    updatedAt: '2024-05-28',
  },
];

export const mockProcedures: Procedure[] = [
  {
    id: 1,
    name: 'Ginecologia',
    slug: 'ginecologia',
    createdAt: '2024-01-01',
    updatedAt: '2024-05-15',
  },
  {
    id: 2,
    name: 'Prevenção',
    slug: 'prevencao',
    createdAt: '2024-01-02',
    updatedAt: '2024-05-16',
  },
  {
    id: 3,
    name: 'Mastologia',
    slug: 'mastologia',
    createdAt: '2024-01-03',
    updatedAt: '2024-05-17',
  },
  {
    id: 4,
    name: 'Reprodução Humana',
    slug: 'reproducao-humana',
    createdAt: '2024-01-04',
    updatedAt: '2024-05-18',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 1,
    doctorId: 1,
    examId: 1,
    date: '2024-06-15',
    startTime: '09:00',
    endTime: '09:30',
    phone: '(11) 98765-4321',
    createdAt: '2024-06-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 2,
    doctorId: 2,
    examId: 2,
    date: '2024-06-16',
    startTime: '10:00',
    endTime: '10:30',
    phone: '(11) 97654-3210',
    createdAt: '2024-06-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 3,
    doctorId: 3,
    examId: 3,
    date: '2024-06-17',
    startTime: '14:00',
    endTime: '14:30',
    phone: '(11) 96543-2109',
    createdAt: '2024-06-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 4,
    doctorId: 1,
    examId: 4,
    date: '2024-06-18',
    startTime: '15:00',
    endTime: '15:30',
    phone: '(11) 95432-1098',
    createdAt: '2024-06-01',
    updatedAt: '2024-06-01',
  },
];

export const mockReviews: Review[] = [
  {
    id: 1,
    rating: 5,
    text: 'Excelente atendimento, recomendo!',
    status: true,
    createdAt: '2024-05-28',
    updatedAt: '2024-05-28',
  },
  {
    id: 2,
    rating: 5,
    text: 'Doutora muito competente e atenciosa.',
    status: true,
    createdAt: '2024-05-29',
    updatedAt: '2024-05-29',
  },
  {
    id: 3,
    rating: 4,
    text: 'Bom atendimento, ambiente limpo.',
    status: true,
    createdAt: '2024-05-30',
    updatedAt: '2024-05-30',
  },
  {
    id: 4,
    rating: 3,
    text: 'Atendimento ok, espera um pouco longa.',
    status: false,
    createdAt: '2024-06-01',
    updatedAt: '2024-06-01',
  },
];

export const mockUsers: User[] = [
  {
    id: 1,
    name: 'Admin User',
    email: 'admin@gynocare.com.br',
    role: 'admin',
    status: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 2,
    name: 'Dra. Maria Silva',
    email: 'maria@gynocare.com.br',
    role: 'doctor',
    status: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-06-01',
  },
  {
    id: 3,
    name: 'Secretária Joana',
    email: 'joana@gynocare.com.br',
    role: 'secretary',
    status: true,
    createdAt: '2024-02-10',
    updatedAt: '2024-05-28',
  },
  {
    id: 4,
    name: 'Dra. Ana Santos',
    email: 'ana@gynocare.com.br',
    role: 'doctor',
    status: true,
    createdAt: '2024-02-10',
    updatedAt: '2024-06-01',
  },
];

export const dashboardModules: DashboardModule[] = [
  {
    id: 'doctors',
    title: 'Médicos',
    description: 'Gerenciar médicos e especialistas',
    icon: '👨‍⚕️',
    href: '/adm/medicos',
    color: 'bg-(--main-color)',
    count: mockDoctors.length,
  },
  {
    id: 'exams',
    title: 'Exames',
    description: 'Gerenciar exames e procedimentos',
    icon: '🔬',
    href: '/adm/exames',
    color: 'bg-(--secondary-color)',
    count: mockExams.length,
  },
  {
    id: 'procedures',
    title: 'Procedimentos',
    description: 'Gerenciar tipos de procedimentos',
    icon: '⚕️',
    href: '/adm/procedimentos',
    color: 'bg-(--main-light-color)',
    count: mockProcedures.length,
  },
  {
    id: 'appointments',
    title: 'Agendamentos',
    description: 'Gerenciar agendamentos de pacientes',
    icon: '📅',
    href: '/adm/agendamentos',
    color: 'bg-(--light-color)',
    count: mockAppointments.length,
  },
  {
    id: 'reviews',
    title: 'Avaliações',
    description: 'Gerenciar avaliações de pacientes',
    icon: '⭐',
    href: '/adm/avaliacoes',
    color: 'bg-(--main-dark-color)',
    count: mockReviews.length,
  },
  {
    id: 'users',
    title: 'Usuários',
    description: 'Gerenciar usuários do sistema',
    icon: '👥',
    href: '/adm/usuarios',
    color: 'bg-(--dark-color)',
    count: mockUsers.length,
  },
];
